apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-marketplace-ibm-entitlement-key
spec:
  destination:
    namespace: openshift-marketplace
    server: https://kubernetes.default.svc
  project: 1-infrastructure
  source:
    path: >-
      payload/1-infrastructure/namespace/openshift-marketplace/ibm-entitlement-key
    repoURL: https://github.com/vijayksorg/gitops-test-cp4s
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
